//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskbar11.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taskbar11.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically Hide Taskbar ähnelt.
        /// </summary>
        public static string AutomaticallyHideTaskbar {
            get {
                return ResourceManager.GetString("AutomaticallyHideTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom ähnelt.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Center ähnelt.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chat ähnelt.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context Menu ähnelt.
        /// </summary>
        public static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t forget to apply and save the settings by pressing the bottom &quot;Save&quot; button. ähnelt.
        /// </summary>
        public static string DonTForgetToApplyAndSaveTheSettingsByPressingTheBottomSaveButton {
            get {
                return ResourceManager.GetString("DonTForgetToApplyAndSaveTheSettingsByPressingTheBottomSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Toolbar ähnelt.
        /// </summary>
        public static string EnableToolbar {
            get {
                return ResourceManager.GetString("EnableToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Equal Taskbar Positions ähnelt.
        /// </summary>
        public static string EqualTaskbarPositions {
            get {
                return ResourceManager.GetString("EqualTaskbarPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Landscape ähnelt.
        /// </summary>
        public static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Large ähnelt.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left ähnelt.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium ähnelt.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multi Monitor Taskbar ähnelt.
        /// </summary>
        public static string MultiMonitorTaskbar {
            get {
                return ResourceManager.GetString("MultiMonitorTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pen ähnelt.
        /// </summary>
        public static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portrait ähnelt.
        /// </summary>
        public static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Secondary Taskbars ähnelt.
        /// </summary>
        public static string ShowSecondaryTaskbars {
            get {
                return ResourceManager.GetString("ShowSecondaryTaskbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small ähnelt.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tablet Options ähnelt.
        /// </summary>
        public static string TabletOptions {
            get {
                return ResourceManager.GetString("TabletOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskbar Behaviour ähnelt.
        /// </summary>
        public static string TaskbarBehaviour {
            get {
                return ResourceManager.GetString("TaskbarBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskbar Corner Icons ähnelt.
        /// </summary>
        public static string TaskbarCornerIcons {
            get {
                return ResourceManager.GetString("TaskbarCornerIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskbar Indentation ähnelt.
        /// </summary>
        public static string TaskbarIndentation {
            get {
                return ResourceManager.GetString("TaskbarIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskbar Items ähnelt.
        /// </summary>
        public static string TaskbarItems {
            get {
                return ResourceManager.GetString("TaskbarItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskbar Position ähnelt.
        /// </summary>
        public static string TaskbarPosition {
            get {
                return ResourceManager.GetString("TaskbarPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taskbar Size ähnelt.
        /// </summary>
        public static string TaskbarSize {
            get {
                return ResourceManager.GetString("TaskbarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task View ähnelt.
        /// </summary>
        public static string TaskView {
            get {
                return ResourceManager.GetString("TaskView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Toolbar can be moved by clicking on the pushpin icon and holding left mouse button, followed by dragging the mouse to the desired position. ähnelt.
        /// </summary>
        public static string TheToolbarCanBeMovedByClickingOnThePushpinIconAndHoldingLeftMouseButtonFollowedByDraggingTheMouseToTheDesiredPosition {
            get {
                return ResourceManager.GetString("TheToolbarCanBeMovedByClickingOnThePushpinIconAndHoldingLeftMouseButtonFollowedBy" +
                        "DraggingTheMouseToTheDesiredPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toolbar Settings ähnelt.
        /// </summary>
        public static string ToolbarSettings {
            get {
                return ResourceManager.GetString("ToolbarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top ähnelt.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Touch Keyboard ähnelt.
        /// </summary>
        public static string TouchKeyboard {
            get {
                return ResourceManager.GetString("TouchKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Old Context Menu For Right Mouse Button Click ähnelt.
        /// </summary>
        public static string UseOldContextMenuForRightMouseButtonClick {
            get {
                return ResourceManager.GetString("UseOldContextMenuForRightMouseButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use Orientation Dependant Taskbar Position ähnelt.
        /// </summary>
        public static string UseOrientationDependantTaskbarPosition {
            get {
                return ResourceManager.GetString("UseOrientationDependantTaskbarPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Virtual Touchpad ähnelt.
        /// </summary>
        public static string VirtualTouchpad {
            get {
                return ResourceManager.GetString("VirtualTouchpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Widgets ähnelt.
        /// </summary>
        public static string Widgets {
            get {
                return ResourceManager.GetString("Widgets", resourceCulture);
            }
        }
    }
}
